# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-05 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=120)),
                ('officeType', models.CharField(blank=True, max_length=120)),
                ('Deliverystatus', models.CharField(blank=True, max_length=120)),
                ('divisionname', models.CharField(blank=True, max_length=120)),
                ('regionname', models.CharField(blank=True, max_length=120)),
                ('circlename', models.CharField(blank=True, max_length=120)),
                ('Taluk', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('state_name', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
