# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-05 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PincodeSearch', '0002_statecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincode',
            old_name='Deliverystatus',
            new_name='Delivery_status',
        ),
        migrations.RenameField(
            model_name='pincode',
            old_name='circlename',
            new_name='circle_name',
        ),
        migrations.RenameField(
            model_name='pincode',
            old_name='divisionname',
            new_name='division_name',
        ),
        migrations.RenameField(
            model_name='pincode',
            old_name='officeType',
            new_name='office_Type',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='regionname',
        ),
        migrations.AddField(
            model_name='pincode',
            name='region_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
