# Generated by Django 2.1.1 on 2018-09-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PincodeSearch', '0003_auto_20180905_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateCode',
        ),
    ]
